image: Visual Studio 2022
configuration: Release

init:
  - git config --global core.autocrlf false

before_build:
  - nuget restore

build:
  verbosity: minimal

after_build:
  - dotnet pack -c Release -o ./artifacts

test:
  assemblies:
    - '**\*Test.dll'

artifacts:
- path: artifacts\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: 77wpGvu/VlncfwO5hMozDOVshlpOQp9dzBbxI+ZfZuEawfDNQ98rM8R0YTL2BXq6