image: Visual Studio 2019
configuration: Release

before_build:
  - nuget restore

build:
  verbosity: minimal

test:
  assemblies:
    - '**\*Test.dll'

deploy:
  provider: NuGet
  api_key:
    secure: D/rtGiK2gMCJU7kBILUjUDMDfKsVqq2S3+ggEJ3n6HG/w/oko66J8/ikeaJIb6lv